name: pic2text
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=23.3
  - cudatoolkit=11.3
  - pytorch=1.9.1
  - torchvision=0.10.1
  - pip:
    - pytorch-lightning==2.1.2
    - "lightning[pytorch-extra]"
    - transformers==4.35.2
    - nltk==3.8.1
    - rouge==1.0.1
    - -e .
