model:
  class_path: dpm.models.p2t.Pic2TextModel
  init_args:
    learning_rate: 0.0005
    lossconfig:
      class_path: torch.nn.CrossEntropyLoss
      init_args:
    ecconfig:
      class_path: dpm.modules.encoder.ViTencoder
      init_args:
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        intermediate_size: 3072
        image_size: 224
        patch_size: 16
        num_channels: 3
        type: 'patch'
    dcconfig:
      class_path: dpm.modules.decoder.Decoder_only
      init_args:
        d_model: 768
        num_head: 8
        num_layer: 6
    ckpt_path: null
    ignore_keys: []
    input_key: "image"
    gt_key: "description_vectors"

data:
  class_path: main.DataModuleFromConfig
    batch_size: 32
    train: 
      class_path: dpm.data.word2vec.ImageTextDataset
      init_args: 
        path
      wrap: false
      num_workers: 64
      pin_memory: true
      prefetch_factor: 4

trainer:
    max_epochs: 500
    benchmark: True

seed_everything: 42
ckpt_path: null
      