model:
  class_path: dpm.models.p2t.Pic2TextModel
  init_args:
    learning_rate: 5.0e-05
    loss:
      target: torch.nn.CrossEntropyLoss
      params:
        ignore_index: 0
    ecconfig:
      target: dpm.modules.encoder.ResNet101Encoder
      params:
        embed_dim: 512
    dcconfig:
      target: dpm.modules.decoder.Encoder_Decoder
      params:
        d_model: 512
        nhead: 64
        num_encoder_layers: 6
        num_decoder_layers: 8
        dim_feedforward: 2048
        dropout: 0.3
    ckpt_path: null
    embed_dim: 512
    gen_strategy: "greedy"
    train_strategy: 'sample'


data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 16
    train:
      target: dpm.data.word2vec.ImageTextDataset
      params:
        json_file_path: './data/deepfashion-multimodal/train_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [ 224,224 ]
    validation:
      target: dpm.data.word2vec.ImageTextDataset
      params:
        json_file_path: './data/test_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [ 224,224 ]
    collect_fn:
      target: dpm.data.word2vec.datapreprocess
    wrap: false
    num_workers: 6
    pin_memory: False
    prefetch_factor: 2
trainer:
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 5
  max_epochs: 31
  benchmark: True
seed_everything: 42
ckpt_path: null