model:
  class_path: dpm.models.p2t.Pic2TextModel
  init_args:
    learning_rate: 5.0e-06
    loss: 
      target: torch.nn.CrossEntropyLoss
      params: 
        ignore_index: 0
    ecconfig:
      target: dpm.modules.encoder.Swinv2encoder
      params:
        image_size:
        - 768
        - 512
        patch_size: 16
        num_channels: 3
        embed_dim: 64
        depths:
        - 10
        - 12
        - 12
        - 14
        - 14
        num_heads:
        - 32
        - 32
        - 64
        - 64
        - 64
        window_size: 9
        mlp_ratio: 4.0
        qkv_bias: true
        hidden_dropout_prob: 0.1
        attention_probs_dropout_prob: 0.1
        drop_path_rate: 0.1
        hidden_act: gelu
        use_absolute_embeddings: false
        initializer_range: 0.02
        layer_norm_eps: 1.0e-05
        encoder_stride: 32
        type: patch
    dcconfig:
      target: dpm.modules.decoder.Decoder_only
      params:
        d_model: 1024
        num_head: 64
        num_layer: 8
        layer_dim_forward: 3072
        layer_dropout: 0.2
        layer_activation: gelu
    embed_dim: 1024
    vocabulary_path: ./data/vocabulary.json
    ckpt_path: null
    ignore_keys: []
    image_key: image
    gt_key: indices
    gt_text: description
    gen_strategy: beam
    train_strategy: 'sample' #sample--schema sampling #forcing teacher forcing

data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 10
    train: 
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/deepfashion-multimodal/train_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size:
        - 768
        - 512
    validation:
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/test_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size:
        - 768
        - 512
    collect_fn: 
      target: dpm.data.word2vec.datapreprocess
    wrap: false
    num_workers: 16
    pin_memory: False
    prefetch_factor: 2
trainer:
    num_sanity_val_steps: 0
    check_val_every_n_epoch: 15
    max_epochs: 46
    benchmark: True
seed_everything: 43
ckpt_path: null
      