model:
  class_path: dpm.models.p2t.Pic2TextModel
  init_args:
    learning_rate: 5.0e-05
    loss: 
      target: torch.nn.CrossEntropyLoss
      params: 
        ignore_index: 0
    ecconfig:
      target: dpm.modules.encoder.Swinv2encoder
      params:
        image_size: [512,256]
        patch_size: 32
        num_channels: 3
        embed_dim: 128
        depths: [2,2,6]
        num_heads: [4,8,8]
        window_size: 7
        mlp_ratio: 4.0
        qkv_bias: true
        hidden_dropout_prob: 0.0
        attention_probs_dropout_prob: 0.0
        drop_path_rate: 0.1
        hidden_act: "gelu"
        use_absolute_embeddings: false
        initializer_range: 0.02
        layer_norm_eps: 1e-5
        encoder_stride: 32
        type: "patch"
    dcconfig:
      target: dpm.modules.decoder.Decoder_only
      params:
        d_model: 512
        num_head: 8
        num_layer: 6
        layer_dim_forward: 2048
        layer_dropout: 0.4
        layer_activation: "gelu"
    ckpt_path: null
    embed_dim: 512
    gen_strategy: "greedy"

data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 8
    train: 
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/deepfashion-multimodal/train_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [512,256]
    validation:
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/test_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [512,256]
    collect_fn: 
      target: dpm.data.word2vec.datapreprocess
    wrap: false
    num_workers: 16
    pin_memory: False
    prefetch_factor: 2
trainer:
    check_val_every_n_epoch: 5
    max_epochs: 30
    benchmark: True
seed_everything: 42
ckpt_path: null
      