model:
  class_path: dpm.models.p2t.Pic2TextModel
  init_args:
    learning_rate: 5.0e-06
    loss: 
      target: torch.nn.CrossEntropyLoss
      params: 
        ignore_index: 0
    ecconfig:
      target: dpm.modules.encoder.VGG19
      params:
        embed_dim: 1024
    dcconfig:
      target: dpm.modules.decoder.Encoder_Decoder
      params:
        d_model: 1024
        nhead: 64
        num_encoder_layers: 12
        num_decoder_layers: 14
        dim_feedforward: 3072
        dropout: 0.3
    ckpt_path: null
    embed_dim: 1024
    gen_strategy: "beam"
    train_strategy: 'sample' #sample--schema sampling #forcing teacher forcing

data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 8
    train: 
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/train_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [512,374]
    validation:
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/test_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [512,374]
    collect_fn: 
      target: dpm.data.word2vec.datapreprocess
    wrap: false
    num_workers: 16
    pin_memory: False
    prefetch_factor: 2
trainer:
    num_sanity_val_steps: 0
    check_val_every_n_epoch: 10
    max_epochs: 46
    benchmark: True
seed_everything: 43
ckpt_path: null
      