model:
  class_path: dpm.models.p2t.Pic2TextModel
  init_args:
    learning_rate: 4.5e-06
    loss: 
      target: torch.nn.CrossEntropyLoss
      params: 
        ignore_index: 0
    ecconfig:
      target: dpm.modules.encoder.ViTencoder
      params:
        hidden_size: 768
        num_hidden_layers: 14
        num_attention_heads: 64
        intermediate_size: 3072
        image_size: [512,374]
        patch_size: 16
        num_channels: 3
        type: 'patch'
    dcconfig:
      target: dpm.modules.decoder.Decoder_only
      params:
        d_model: 768
        num_head: 64
        num_layer: 8
        layer_dim_forward: 3072
        layer_dropout: 0.3
        layer_activation: "gelu"
    ckpt_path: null
    embed_dim: 768
    gen_strategy: "beam"
    train_strategy: 'forcing' #sample--schema sampling #forcing teacher forcing

data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 8
    train: 
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/deepfashion-multimodal/train_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [512,374]
    validation:
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/test_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [512,374]
    collect_fn: 
      target: dpm.data.word2vec.datapreprocess
    wrap: false
    num_workers: 16
    pin_memory: False
    prefetch_factor: 2
trainer:
    check_val_every_n_epoch: 4
    max_epochs: 37
    benchmark: True
seed_everything: 43
ckpt_path: null
      