model:
  class_path: dpm.models.p2t.Pic2TextModel
  init_args:
    learning_rate: 5.0e-05
    loss: 
      target: torch.nn.CrossEntropyLoss
      params: 
        ignore_index: 0
    ecconfig:
      target: dpm.modules.encoder.ViTencoder
      params:
        hidden_size: 512
        num_hidden_layers: 6
        num_attention_heads: 8
        intermediate_size: 2048
        image_size: [512,374]
        patch_size: 32
        num_channels: 3
        type: 'patch'
    dcconfig:
      target: dpm.modules.decoder.Decoder_only
      params:
        d_model: 512
        num_head: 8
        num_layer: 6
        layer_dim_forward: 2048
        layer_dropout: 0.2
        layer_activation: "gelu"
    ckpt_path: null
    embed_dim: 512
    gen_strategy: "beam"
    train_strategy: 'sample' #sample--schema sampling #forcing teacher forcing

data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 4
    train: 
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/deepfashion-multimodal/train_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [512,374]
    validation:
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/test_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [512,374]
    collect_fn: 
      target: dpm.data.word2vec.datapreprocess
    wrap: false
    num_workers: 8
    pin_memory: False
    prefetch_factor: 2
trainer:
    check_val_every_n_epoch: 3
    max_epochs: 36
    benchmark: True
seed_everything: 42
ckpt_path: null
      