model:
  class_path: dpm.models.p2t.Pic2TextModel
  init_args:
    learning_rate: 5.0e-05
    loss: 
      target: torch.nn.CrossEntropyLoss
      params: 
        ignore_index: 0
    ecconfig:
      target: dpm.modules.encoder.ViTencoder
      params:
        hidden_size: 768
        num_hidden_layers: 8
        num_attention_heads: 8
        intermediate_size: 3072
        image_size: [768,512]
        patch_size: 32
        num_channels: 3
        type: 'patch'
    dcconfig:
      target: dpm.modules.decoder.Decoder_only
      params:
        d_model: 768
        num_head: 8
        num_layer: 12
    ckpt_path: null
    embed_dim: 768
    gen_strategy: "greedy"

data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 8
    train: 
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/deepfashion-multimodal/train_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [768,512]
    validation:
      target: dpm.data.word2vec.ImageTextDataset
      params: 
        json_file_path: './data/test_captions.json'
        image_folder_path: './data/deepfashion-multimodal/images'
        image_size: [768,512]
    collect_fn: 
      target: dpm.data.word2vec.datapreprocess
    wrap: false
    num_workers: 6
    pin_memory: False
    prefetch_factor: 2
trainer:
    check_val_every_n_epoch: 3
    max_epochs: 30
    benchmark: True
seed_everything: 42
ckpt_path: null
      